name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.413  
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs/tags/v/}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release /p:Version=${VERSION} --no-restore

      - name: Test
        run: dotnet test -c Release /p:Version=${VERSION} --no-build

      - name: Pack
        run: dotnet pack -c Release -o ./packages /p:Version=${VERSION} --no-build

      - name: Store Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: hazelnutNuget
          path: ./packages/*.nupkg

      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: hazelnutNuget

      - name: Push
        run: dotnet nuget push *.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{secrets.NUGET_API_KEY}} \
          --skip-duplicate
